module.exports = {
  apps: [
    {
      name: "specs-1-7471",
      script: "./enrich_variants_with_specs.js",
      args: "--start_line 1 --end_line 7471",
      autorestart: true,
      watch: false,
      max_restarts: 10,
      restart_delay: 2000,
      time: true,
    },
    {
      name: "specs-7472-14942",
      script: "./enrich_variants_with_specs.js",
      args: "--start_line 7472 --end_line 14942",
      autorestart: true,
      watch: false,
      max_restarts: 10,
      restart_delay: 2000,
      time: true,
    },
    {
      name: "specs-14943-22413",
      script: "./enrich_variants_with_specs.js",
      args: "--start_line 14943 --end_line 22413",
      autorestart: true,
      watch: false,
      max_restarts: 10,
      restart_delay: 2000,
      time: true,
    },
    {
      name: "specs-22414-29884",
      script: "./enrich_variants_with_specs.js",
      args: "--start_line 22414 --end_line 29884",
      autorestart: true,
      watch: false,
      max_restarts: 10,
      restart_delay: 2000,
      time: true,
    },
    {
      name: "specs-29885-37354",
      script: "./enrich_variants_with_specs.js",
      args: "--start_line 29885 --end_line 37354",
      autorestart: true,
      watch: false,
      max_restarts: 10,
      restart_delay: 2000,
      time: true,
    },
  ],
};
